export const copy = {
  emptyOffers:     'Aún no tienes ofertas disponibles. La empresa te enviará viajes pronto.',
  emptyTrips:      'No tienes viajes activos. Acepta una oferta para comenzar.',
  emptyDocs:       'Este viaje no tiene documentos de la empresa todavía.',
  emptyDrivers:    'Aún no hay conductores registrados. Crea el primero y genera su código de acceso.',
  emptyTripsDisp:  'No hay viajes creados. Crea el primero para comenzar a asignar conductores.',
  emptyCodes:      'Los códigos generados aparecerán aquí.',
  docSubmitted:    'Tu documento fue enviado y está en revisión. Te avisamos cuando sea revisado.',
  docApproved:     'Documento aprobado ✓',
  docRejected:     'La empresa rechazó este documento. Revisa el motivo y vuelve a enviarlo.',
  noFileSelected:  'Selecciona un archivo antes de subirlo.',
  uploadSuccess:   'Documento enviado. La empresa lo revisará pronto.',
  codeInvalid:     'El código no es válido. Pide uno nuevo a la empresa.',
  codeUsed:        'Este código ya fue usado. Si crees que es un error, contacta a la empresa.',
  codeExpired:     'El código expiró. Solicita un nuevo código a la empresa.',
  accessActivated: '¡Acceso activado! Ya puedes ver tus viajes y documentos.',
  networkError:    'No se pudo cargar la información. Revisa tu conexión y vuelve a intentarlo.',
  demoDoc:         'Documento demo sin archivo',
};
